[helpers]

[default]
depends = []

[default.files]
"packages/ghostty/config" = "~/.config/ghostty/config"
"packages/nvim" = "~/.config/nvim"

[default.variables]

[settings]
default_target_type = "automatic"
