[helpers]

[default]
depends = []

[default.files]
"packages/ghostty/config" = "~/.config/ghostty/config"
"packages/nvim" = "~/.config/nvim"
"packages/starship/starship.toml" = "~/.config/starship.toml"
"packages/zsh/.zshrc" = "~/.zshrc"

[default.variables]

[settings]
default_target_type = "automatic"
